services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Letkode\CommonBundle\:
        resource: '../src/'
        exclude:
            - '../src/LetkodeCommonBundle.php'
            - '../src/Exception/'
            - '../src/Attribute/Mapping/'
